from 候選句.交叉二維揣候選句 import 交叉二維揣候選句
from 候選句.交叉二維揣候選句 import 詞相關評價
from 候選句.建立候選句佮對應句關係 import 候選句佮對應句對照
from 候選句.建立候選句佮對應句關係 import 建立候選句佮對應句關係
from 候選句.建立候選句佮對應句關係 import 提出對照位置
from 候選句.建立候選句佮對應句關係 import 調整對照
from 剖析相關工具.剖析工具 import 剖析工具
from 剖析相關工具.剖析結構化工具 import 剖析結構化工具
from 剖析相關工具.剖析結構化工具 import 印出
from 剖析相關工具.官方剖析工具 import 官方剖析工具
from 剖析相關工具.自設剖析工具 import 自設剖析工具
from 教會系羅馬音標 import 教會系羅馬音標
from 教會羅馬字音標 import 教會羅馬字音標
from 教會羅馬字音標 import 教會羅馬字音標聲母表
from 教會羅馬字音標 import 教會羅馬字音標韻母表
from 教育部臺灣客家語常用詞辭典.客話辭典網頁剖析工具 import 客話辭典網頁剖析工具
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 俗音記號
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 偏泉優勢音腔口
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 偏漳優勢音腔口
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 加文字
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 加演化
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 加關係
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 合音記號
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 國語臺員腔
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 字方言差欄位
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣主條目
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣字方言差
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣文字上大流水號
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣文白流水號
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣義倒詞的詞音
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣義倒詞組合
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣義近詞的詞音
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣義近詞組合
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣詞俗音
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣詞別音
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣詞合音
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣詞方言差
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣釋義
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 揣關係上大流水號
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 會當替換
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 用主碼號揣流水號
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 用流水號揣腔口
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 用釋義揣例句
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 空白符號
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 義近
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 袂當替換
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 設定來源
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 設定合音遏袂處理
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 設定文字組合
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 設定無音文字
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 設定編修狀況
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 設定詞性
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 詞性對照表
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 詞方言差欄位
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 資料庫連線
from 教育部臺灣閩南語常用詞辭典.資料庫連線 import 隔開符號
from 教育部臺灣閩南語常用詞辭典.造字處理 import 共造字換做統一碼表示法
from 教育部臺灣閩南語常用詞辭典.造字處理 import 解析器
from 整理中的台語詞典.詞六國語通用拼音轉注音符號表 import 通用佮注音聲韻轉換表
from 整理中的台語詞典.詞六國語通用拼音轉注音符號表 import 通用佮注音調轉換表
from 文章音標解析器 import 文章音標解析器
from 新酷音輸入法.字表整理 import 整理字表
from 新酷音輸入法.詞庫整理 import 整理詞庫
from 方音符號吳守禮改良式 import 方音符號吳守禮改良式
from 方音符號吳守禮改良式 import 方音符號吳守禮改良式
from 服務架設.連線控制器 import 連線控制器
from 標音系統整合.句綜合標音 import 句綜合標音
from 標音系統整合.標音整合 import 標音整合
from 標音系統整合.詞組綜合標音 import 詞組綜合標音
from 標音系統整合.閩南語綜合標音 import 閩南語字詞綜合標音
from 標音資料庫工具.揣音標 import 揣腔口型體資料
from 標音資料庫工具.揣音標 import 揣言語層的字詞
from 系統整合.翻譯整合 import 翻譯整合
from 臺灣語言音標 import 臺灣語言音標
from 臺灣語言音標 import 臺灣語言音標
from 臺灣閩南語羅馬字拼音 import 臺灣閩南語羅馬字拼音
from 臺灣閩南語羅馬字拼音 import 臺灣閩南語羅馬字拼音
from 臺灣閩南語羅馬字拼音 import 臺灣閩南語羅馬字拼音韻母表
from 華語台語雙語語料庫系統.何澤政教會羅馬字音標 import 何澤政教會羅馬字音標
from 華語台語雙語語料庫系統.何澤政教會羅馬字音標 import 何澤政教會羅馬字音標
from 華語台語雙語語料庫系統.文章標點處理工具 import 文章標點處理工具
from 言語資料庫.公用資料 import 加文字佮版本
from 言語資料庫.公用資料 import 加文字佮組合佮版本
from 言語資料庫.公用資料 import 加編修狀況
from 言語資料庫.公用資料 import 國語腔口
from 言語資料庫.公用資料 import 字詞
from 言語資料庫.公用資料 import 揣出組合中流水號的實際文字流水號
from 言語資料庫.公用資料 import 揣文字上大流水號
from 言語資料庫.公用資料 import 文字組合符號
from 言語資料庫.公用資料 import 文字組合邊界
from 言語資料庫.公用資料 import 會當替換
from 言語資料庫.公用資料 import 標點符號
from 言語資料庫.公用資料 import 版本正常
from 言語資料庫.公用資料 import 版本音標有問題
from 言語資料庫.公用資料 import 用流水號揣文字
from 言語資料庫.公用資料 import 用流水號揣編修
from 言語資料庫.公用資料 import 章表冊
from 言語資料庫.公用資料 import 組字式符號
from 言語資料庫.公用資料 import 義近
from 言語資料庫.公用資料 import 臺員
from 言語資料庫.公用資料 import 臺語腔口
from 言語資料庫.公用資料 import 語句
from 言語資料庫.公用資料 import 資料庫連線
from 言語資料庫.常用方法 import 展開
from 言語資料庫.常用方法 import 提掉空白
from 資料庫工具.型體翻譯 import 型體翻譯
from 通用拼音佮臺灣語言音標調類對照表 import 臺羅對通用聲韻對照表
from 通用拼音佮臺灣語言音標調類對照表 import 臺羅對通用調對照表
from 通用拼音佮臺灣語言音標調類對照表 import 通用拼音佮臺灣語言音標聲韻對照表, 通用拼音佮臺灣語言音標調類對照表
from 通用拼音音標 import 通用拼音音標
from 通用拼音音標 import 通用拼音音標
from 閩南資料.國閩字詞翻譯 import 國閩單位結構化翻譯
from 閩南資料.國閩字詞翻譯 import 國閩單位翻譯
from 閩南資料.國閩字詞翻譯 import 字音結構化
from 閩南資料.國閩字詞翻譯 import 翻譯佮詞性語意字音結構化
from 閩南資料.字 import 字
from 閩南資料.詞 import 用字產生詞
from 閩南資料.詞 import 詞
from 音標介面 import 音標介面